<a href="https://colab.research.google.com/github/shiveshhcodes/python-functions-colab/blob/main/filter_map_reduce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def filter_even(numbers):
  return list(filter(lambda x: x % 2 == 0, numbers))

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 44, 56,34,65,23,78]
print(filter_even(nums))

[2, 4, 6, 8, 10, 44, 56, 34, 78]


In [ ]:
def square_numbers(numbers):
  return list(map(lambda x: x ** 2, numbers))

numbers = [1,2,3,4,5,6,7,8]
print(square_numbers(numbers))

[1, 4, 9, 16, 25, 36, 49, 64]


In [ ]:
from functools import reduce

def sum_numbers(numbers):
  return reduce(lambda x,y: x+y, numbers)

numbers = [1,2,3,4,5,6,7,8]
print(sum_numbers(nums))

355


In [ ]:
nums_dict = {x: x**3 for x in range(1,21)}
print(nums_dict)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000, 11: 1331, 12: 1728, 13: 2197, 14: 2744, 15: 3375, 16: 4096, 17: 4913, 18: 5832, 19: 6859, 20: 8000}


In [23]:
import numpy as np
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)

np2 = np.arange(10)
print(np2)

np3 = np.arange(0,33,3)
print(np3)

np4 = np.arange(0,10,0.5)
print(np4)

np5 = np.zeros((2,10))
print(np5)

np6 = np.full((2,10), 5)
print(np6)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27 30]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]
